#!/bin/bash

#  normal traffic
echo "Testing normal traffic..."
curl -X POST http://localhost:5000/check \
-H "Content-Type: application/json" \
-d '{
    "packet_size": 512,
    "packet_rate": 1.2,
    "protocol_type": 0,
    "duration": 0.5,
    "src_bytes": 342,
    "dst_bytes": 234,
    "wrong_fragment": 0,
    "urgent": 0,
    "hot": 0,
    "num_failed_logins": 0,
    "logged_in": 1,
    "num_compromised": 0,
    "root_shell": 0,
    "su_attempted": 0,
    "num_root": 0,
    "num_file_creations": 0,
    "num_shells": 0,
    "num_access_files": 0,
    "num_outbound_cmds": 0,
    "is_host_login": 0,
    "is_guest_login": 0,
    "count": 10,
    "srv_count": 8,
    "serror_rate": 0.05,
    "srv_serror_rate": 0.03,
    "rerror_rate": 0.01,
    "srv_rerror_rate": 0.01,
    "same_srv_rate": 0.85,
    "diff_srv_rate": 0.15,
    "srv_diff_host_rate": 0.1,
    "dst_host_count": 25,
    "dst_host_srv_count": 20,
    "dst_host_same_srv_rate": 0.9,
    "dst_host_diff_srv_rate": 0.1,
    "dst_host_same_src_port_rate": 0.8,
    "dst_host_srv_diff_host_rate": 0.15,
    "dst_host_serror_rate": 0.05,
    "dst_host_srv_serror_rate": 0.03,
    "dst_host_rerror_rate": 0.01,
    "dst_host_srv_rerror_rate": 0.01
}'

echo -e "\n\nTesting DDoS attack..."
curl -X POST http://localhost:5000/check \
-H "Content-Type: application/json" \
-d '{
    "packet_size": 64,
    "packet_rate": 850.0,
    "protocol_type": 0,
    "duration": 0.05,
    "src_bytes": 120,
    "dst_bytes": 0,
    "wrong_fragment": 1,
    "urgent": 0,
    "hot": 0,
    "num_failed_logins": 0,
    "logged_in": 0,
    "num_compromised": 0,
    "root_shell": 0,
    "su_attempted": 0,
    "num_root": 0,
    "num_file_creations": 0,
    "num_shells": 0,
    "num_access_files": 0,
    "num_outbound_cmds": 0,
    "is_host_login": 0,
    "is_guest_login": 0,
    "count": 500,
    "srv_count": 500,
    "serror_rate": 0.8,
    "srv_serror_rate": 0.8,
    "rerror_rate": 0.7,
    "srv_rerror_rate": 0.7,
    "same_srv_rate": 0.1,
    "diff_srv_rate": 0.9,
    "srv_diff_host_rate": 0.9,
    "dst_host_count": 800,
    "dst_host_srv_count": 800,
    "dst_host_same_srv_rate": 0.1,
    "dst_host_diff_srv_rate": 0.9,
    "dst_host_same_src_port_rate": 0.1,
    "dst_host_srv_diff_host_rate": 0.9,
    "dst_host_serror_rate": 0.8,
    "dst_host_srv_serror_rate": 0.8,
    "dst_host_rerror_rate": 0.7,
    "dst_host_srv_rerror_rate": 0.7
}'

echo -e "\n\nTesting spoofing attack..."
curl -X POST http://localhost:5000/check \
-H "Content-Type: application/json" \
-d '{
    "packet_size": 1024,
    "packet_rate": 3.5,
    "protocol_type": 0,
    "duration": 0.7,
    "src_bytes": 450,
    "dst_bytes": 320,
    "wrong_fragment": 3,
    "urgent": 1,
    "hot": 3,
    "num_failed_logins": 3,
    "logged_in": 0,
    "num_compromised": 2,
    "root_shell": 1,
    "su_attempted": 1,
    "num_root": 0,
    "num_file_creations": 0,
    "num_shells": 0,
    "num_access_files": 0,
    "num_outbound_cmds": 0,
    "is_host_login": 0,
    "is_guest_login": 1,
    "count": 15,
    "srv_count": 12,
    "serror_rate": 0.5,
    "srv_serror_rate": 0.5,
    "rerror_rate": 0.4,
    "srv_rerror_rate": 0.4,
    "same_srv_rate": 0.5,
    "diff_srv_rate": 0.5,
    "srv_diff_host_rate": 0.5,
    "dst_host_count": 30,
    "dst_host_srv_count": 25,
    "dst_host_same_srv_rate": 0.5,
    "dst_host_diff_srv_rate": 0.5,
    "dst_host_same_src_port_rate": 0.5,
    "dst_host_srv_diff_host_rate": 0.5,
    "dst_host_serror_rate": 0.5,
    "dst_host_srv_serror_rate": 0.5,
    "dst_host_rerror_rate": 0.4,
    "dst_host_srv_rerror_rate": 0.4
}'
